// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: controllers.sql

package sqlc

import (
	"context"
)

const countControllerByName = `-- name: CountControllerByName :one
SELECT COUNT(*)
FROM controllers
WHERE namespace_id = ? AND name = ?
`

type CountControllerByNameParams struct {
	NamespaceID string `json:"namespace_id"`
	Name        string `json:"name"`
}

func (q *Queries) CountControllerByName(ctx context.Context, arg CountControllerByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countControllerByName, arg.NamespaceID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createController = `-- name: CreateController :exec
INSERT INTO controllers(namespace_id, name, details_json)
VALUES (?, ?, ?)
`

type CreateControllerParams struct {
	NamespaceID string `json:"namespace_id"`
	Name        string `json:"name"`
	DetailsJson string `json:"details_json"`
}

func (q *Queries) CreateController(ctx context.Context, arg CreateControllerParams) error {
	_, err := q.db.ExecContext(ctx, createController, arg.NamespaceID, arg.Name, arg.DetailsJson)
	return err
}

const deleteController = `-- name: DeleteController :exec
DELETE FROM controllers
WHERE namespace_id = ? AND name = ?
`

type DeleteControllerParams struct {
	NamespaceID string `json:"namespace_id"`
	Name        string `json:"name"`
}

func (q *Queries) DeleteController(ctx context.Context, arg DeleteControllerParams) error {
	_, err := q.db.ExecContext(ctx, deleteController, arg.NamespaceID, arg.Name)
	return err
}

const deleteControllerAccessByController = `-- name: DeleteControllerAccessByController :exec
DELETE FROM controller_access
WHERE namespace_id = ? AND controller_name = ?
`

type DeleteControllerAccessByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

func (q *Queries) DeleteControllerAccessByController(ctx context.Context, arg DeleteControllerAccessByControllerParams) error {
	_, err := q.db.ExecContext(ctx, deleteControllerAccessByController, arg.NamespaceID, arg.ControllerName)
	return err
}

const deleteControllerAccessByNamespace = `-- name: DeleteControllerAccessByNamespace :exec
DELETE FROM controller_access
WHERE namespace_id = ?
`

func (q *Queries) DeleteControllerAccessByNamespace(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteControllerAccessByNamespace, namespaceID)
	return err
}

const deleteControllerAccessByUserID = `-- name: DeleteControllerAccessByUserID :exec
DELETE FROM controller_access
WHERE user_id = ?
`

func (q *Queries) DeleteControllerAccessByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteControllerAccessByUserID, userID)
	return err
}

const deleteControllerMetaByNamespace = `-- name: DeleteControllerMetaByNamespace :exec
DELETE FROM controller_meta
WHERE namespace_id = ?
`

func (q *Queries) DeleteControllerMetaByNamespace(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteControllerMetaByNamespace, namespaceID)
	return err
}

const deleteControllerSelectionMeta = `-- name: DeleteControllerSelectionMeta :exec
DELETE FROM controller_meta
WHERE namespace_id = ? AND key IN ('current', 'previous')
`

func (q *Queries) DeleteControllerSelectionMeta(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteControllerSelectionMeta, namespaceID)
	return err
}

const findControllerByEndpoints = `-- name: FindControllerByEndpoints :many
SELECT name, details_json
FROM controllers
WHERE namespace_id = ?
`

type FindControllerByEndpointsRow struct {
	Name        string `json:"name"`
	DetailsJson string `json:"details_json"`
}

func (q *Queries) FindControllerByEndpoints(ctx context.Context, namespaceID string) ([]FindControllerByEndpointsRow, error) {
	rows, err := q.db.QueryContext(ctx, findControllerByEndpoints, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindControllerByEndpointsRow{}
	for rows.Next() {
		var i FindControllerByEndpointsRow
		if err := rows.Scan(&i.Name, &i.DetailsJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getControllerAccess = `-- name: GetControllerAccess :one
SELECT access
FROM controller_access
WHERE namespace_id = ? AND controller_name = ? AND user_id = ?
`

type GetControllerAccessParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetControllerAccess(ctx context.Context, arg GetControllerAccessParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getControllerAccess, arg.NamespaceID, arg.ControllerName, arg.UserID)
	var access string
	err := row.Scan(&access)
	return access, err
}

const getControllerByName = `-- name: GetControllerByName :one
SELECT details_json
FROM controllers
WHERE namespace_id = ? AND name = ?
`

type GetControllerByNameParams struct {
	NamespaceID string `json:"namespace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetControllerByName(ctx context.Context, arg GetControllerByNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getControllerByName, arg.NamespaceID, arg.Name)
	var details_json string
	err := row.Scan(&details_json)
	return details_json, err
}

const getControllerMeta = `-- name: GetControllerMeta :one
SELECT value
FROM controller_meta
WHERE namespace_id = ? AND key = ?
`

type GetControllerMetaParams struct {
	NamespaceID string `json:"namespace_id"`
	Key         string `json:"key"`
}

func (q *Queries) GetControllerMeta(ctx context.Context, arg GetControllerMetaParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getControllerMeta, arg.NamespaceID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listControllersByNamespace = `-- name: ListControllersByNamespace :many
SELECT name, details_json
FROM controllers
WHERE namespace_id = ?
ORDER BY name ASC
`

type ListControllersByNamespaceRow struct {
	Name        string `json:"name"`
	DetailsJson string `json:"details_json"`
}

func (q *Queries) ListControllersByNamespace(ctx context.Context, namespaceID string) ([]ListControllersByNamespaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listControllersByNamespace, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListControllersByNamespaceRow{}
	for rows.Next() {
		var i ListControllersByNamespaceRow
		if err := rows.Scan(&i.Name, &i.DetailsJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const migrateControllerAccessUserID = `-- name: MigrateControllerAccessUserID :exec
INSERT INTO controller_access(namespace_id, controller_name, user_id, access)
SELECT ca.namespace_id, ca.controller_name, ?, ca.access
FROM controller_access AS ca
WHERE ca.user_id = ?
ON CONFLICT(namespace_id, controller_name, user_id) DO NOTHING
`

type MigrateControllerAccessUserIDParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

func (q *Queries) MigrateControllerAccessUserID(ctx context.Context, arg MigrateControllerAccessUserIDParams) error {
	_, err := q.db.ExecContext(ctx, migrateControllerAccessUserID, arg.UserID, arg.UserID_2)
	return err
}

const setControllerAccess = `-- name: SetControllerAccess :exec
INSERT INTO controller_access(namespace_id, controller_name, user_id, access)
VALUES (?, ?, ?, ?)
ON CONFLICT(namespace_id, controller_name, user_id) DO UPDATE SET access = excluded.access
`

type SetControllerAccessParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	UserID         string `json:"user_id"`
	Access         string `json:"access"`
}

func (q *Queries) SetControllerAccess(ctx context.Context, arg SetControllerAccessParams) error {
	_, err := q.db.ExecContext(ctx, setControllerAccess,
		arg.NamespaceID,
		arg.ControllerName,
		arg.UserID,
		arg.Access,
	)
	return err
}

const setControllerMeta = `-- name: SetControllerMeta :exec
INSERT INTO controller_meta(namespace_id, key, value)
VALUES (?, ?, ?)
ON CONFLICT(namespace_id, key) DO UPDATE SET value = excluded.value
`

type SetControllerMetaParams struct {
	NamespaceID string `json:"namespace_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
}

func (q *Queries) SetControllerMeta(ctx context.Context, arg SetControllerMetaParams) error {
	_, err := q.db.ExecContext(ctx, setControllerMeta, arg.NamespaceID, arg.Key, arg.Value)
	return err
}

const updateController = `-- name: UpdateController :exec
UPDATE controllers
SET details_json = ?
WHERE namespace_id = ? AND name = ?
`

type UpdateControllerParams struct {
	DetailsJson string `json:"details_json"`
	NamespaceID string `json:"namespace_id"`
	Name        string `json:"name"`
}

func (q *Queries) UpdateController(ctx context.Context, arg UpdateControllerParams) error {
	_, err := q.db.ExecContext(ctx, updateController, arg.DetailsJson, arg.NamespaceID, arg.Name)
	return err
}
