// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package sqlc

import (
	"context"
)

const createControllerSigningKey = `-- name: CreateControllerSigningKey :exec
INSERT INTO controller_signing_keys(id, key_pem)
VALUES (?, ?)
`

type CreateControllerSigningKeyParams struct {
	ID     string `json:"id"`
	KeyPem string `json:"key_pem"`
}

func (q *Queries) CreateControllerSigningKey(ctx context.Context, arg CreateControllerSigningKeyParams) error {
	_, err := q.db.ExecContext(ctx, createControllerSigningKey, arg.ID, arg.KeyPem)
	return err
}

const createSigningKey = `-- name: CreateSigningKey :exec
INSERT INTO signing_keys(id, key_pem)
VALUES (?, ?)
`

type CreateSigningKeyParams struct {
	ID     string `json:"id"`
	KeyPem string `json:"key_pem"`
}

func (q *Queries) CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) error {
	_, err := q.db.ExecContext(ctx, createSigningKey, arg.ID, arg.KeyPem)
	return err
}

const listActiveControllerSigningKeys = `-- name: ListActiveControllerSigningKeys :many
SELECT id, key_pem, created_at, retired_at
FROM controller_signing_keys
WHERE retired_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveControllerSigningKeys(ctx context.Context) ([]ControllerSigningKey, error) {
	rows, err := q.db.QueryContext(ctx, listActiveControllerSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControllerSigningKey{}
	for rows.Next() {
		var i ControllerSigningKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyPem,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSigningKeys = `-- name: ListActiveSigningKeys :many
SELECT id, key_pem, created_at, retired_at
FROM signing_keys
WHERE retired_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSigningKeys(ctx context.Context) ([]SigningKey, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SigningKey{}
	for rows.Next() {
		var i SigningKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyPem,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControllerSigningKeys = `-- name: ListControllerSigningKeys :many
SELECT id, key_pem, created_at, retired_at
FROM controller_signing_keys
ORDER BY created_at DESC
`

func (q *Queries) ListControllerSigningKeys(ctx context.Context) ([]ControllerSigningKey, error) {
	rows, err := q.db.QueryContext(ctx, listControllerSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControllerSigningKey{}
	for rows.Next() {
		var i ControllerSigningKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyPem,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSigningKeys = `-- name: ListSigningKeys :many
SELECT id, key_pem, created_at, retired_at
FROM signing_keys
ORDER BY created_at DESC
`

func (q *Queries) ListSigningKeys(ctx context.Context) ([]SigningKey, error) {
	rows, err := q.db.QueryContext(ctx, listSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SigningKey{}
	for rows.Next() {
		var i SigningKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyPem,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireControllerSigningKey = `-- name: RetireControllerSigningKey :exec
UPDATE controller_signing_keys
SET retired_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) RetireControllerSigningKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, retireControllerSigningKey, id)
	return err
}

const retireSigningKey = `-- name: RetireSigningKey :exec
UPDATE signing_keys
SET retired_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) RetireSigningKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, retireSigningKey, id)
	return err
}
