// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package sqlc

import (
	"context"
)

const countModelByName = `-- name: CountModelByName :one
SELECT COUNT(*)
FROM models
WHERE namespace_id = ? AND controller_name = ? AND model_name = ?
`

type CountModelByNameParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	ModelName      string `json:"model_name"`
}

func (q *Queries) CountModelByName(ctx context.Context, arg CountModelByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModelByName, arg.NamespaceID, arg.ControllerName, arg.ModelName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModel = `-- name: CreateModel :exec
INSERT INTO models(namespace_id, controller_name, model_name, details_json)
VALUES (?, ?, ?, ?)
`

type CreateModelParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	ModelName      string `json:"model_name"`
	DetailsJson    string `json:"details_json"`
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) error {
	_, err := q.db.ExecContext(ctx, createModel,
		arg.NamespaceID,
		arg.ControllerName,
		arg.ModelName,
		arg.DetailsJson,
	)
	return err
}

const deleteModelByName = `-- name: DeleteModelByName :exec
DELETE FROM models
WHERE namespace_id = ? AND controller_name = ? AND model_name = ?
`

type DeleteModelByNameParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	ModelName      string `json:"model_name"`
}

func (q *Queries) DeleteModelByName(ctx context.Context, arg DeleteModelByNameParams) error {
	_, err := q.db.ExecContext(ctx, deleteModelByName, arg.NamespaceID, arg.ControllerName, arg.ModelName)
	return err
}

const deleteModelMetaByController = `-- name: DeleteModelMetaByController :exec
DELETE FROM model_meta
WHERE namespace_id = ? AND controller_name = ?
`

type DeleteModelMetaByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

func (q *Queries) DeleteModelMetaByController(ctx context.Context, arg DeleteModelMetaByControllerParams) error {
	_, err := q.db.ExecContext(ctx, deleteModelMetaByController, arg.NamespaceID, arg.ControllerName)
	return err
}

const deleteModelMetaByNamespace = `-- name: DeleteModelMetaByNamespace :exec
DELETE FROM model_meta
WHERE namespace_id = ?
`

func (q *Queries) DeleteModelMetaByNamespace(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteModelMetaByNamespace, namespaceID)
	return err
}

const deleteModelsByController = `-- name: DeleteModelsByController :exec
DELETE FROM models
WHERE namespace_id = ? AND controller_name = ?
`

type DeleteModelsByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

func (q *Queries) DeleteModelsByController(ctx context.Context, arg DeleteModelsByControllerParams) error {
	_, err := q.db.ExecContext(ctx, deleteModelsByController, arg.NamespaceID, arg.ControllerName)
	return err
}

const deleteModelsByNamespace = `-- name: DeleteModelsByNamespace :exec
DELETE FROM models
WHERE namespace_id = ?
`

func (q *Queries) DeleteModelsByNamespace(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteModelsByNamespace, namespaceID)
	return err
}

const getModelByName = `-- name: GetModelByName :one
SELECT details_json
FROM models
WHERE namespace_id = ? AND controller_name = ? AND model_name = ?
`

type GetModelByNameParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	ModelName      string `json:"model_name"`
}

func (q *Queries) GetModelByName(ctx context.Context, arg GetModelByNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getModelByName, arg.NamespaceID, arg.ControllerName, arg.ModelName)
	var details_json string
	err := row.Scan(&details_json)
	return details_json, err
}

const getModelBySuffix = `-- name: GetModelBySuffix :one
SELECT details_json
FROM models
WHERE namespace_id = ? AND controller_name = ? AND model_name LIKE ?
`

type GetModelBySuffixParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	ModelName      string `json:"model_name"`
}

func (q *Queries) GetModelBySuffix(ctx context.Context, arg GetModelBySuffixParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getModelBySuffix, arg.NamespaceID, arg.ControllerName, arg.ModelName)
	var details_json string
	err := row.Scan(&details_json)
	return details_json, err
}

const getModelMeta = `-- name: GetModelMeta :one
SELECT value
FROM model_meta
WHERE namespace_id = ? AND controller_name = ? AND key = ?
`

type GetModelMetaParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	Key            string `json:"key"`
}

func (q *Queries) GetModelMeta(ctx context.Context, arg GetModelMetaParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getModelMeta, arg.NamespaceID, arg.ControllerName, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getModelNameBySuffix = `-- name: GetModelNameBySuffix :one
SELECT model_name
FROM models
WHERE namespace_id = ? AND controller_name = ? AND model_name LIKE ?
`

type GetModelNameBySuffixParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	ModelName      string `json:"model_name"`
}

func (q *Queries) GetModelNameBySuffix(ctx context.Context, arg GetModelNameBySuffixParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getModelNameBySuffix, arg.NamespaceID, arg.ControllerName, arg.ModelName)
	var model_name string
	err := row.Scan(&model_name)
	return model_name, err
}

const listModelsByController = `-- name: ListModelsByController :many
SELECT model_name, details_json
FROM models
WHERE namespace_id = ? AND controller_name = ?
ORDER BY model_name ASC
`

type ListModelsByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

type ListModelsByControllerRow struct {
	ModelName   string `json:"model_name"`
	DetailsJson string `json:"details_json"`
}

func (q *Queries) ListModelsByController(ctx context.Context, arg ListModelsByControllerParams) ([]ListModelsByControllerRow, error) {
	rows, err := q.db.QueryContext(ctx, listModelsByController, arg.NamespaceID, arg.ControllerName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelsByControllerRow{}
	for rows.Next() {
		var i ListModelsByControllerRow
		if err := rows.Scan(&i.ModelName, &i.DetailsJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceModelsByController = `-- name: ReplaceModelsByController :exec
DELETE FROM models
WHERE namespace_id = ? AND controller_name = ?
`

type ReplaceModelsByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

func (q *Queries) ReplaceModelsByController(ctx context.Context, arg ReplaceModelsByControllerParams) error {
	_, err := q.db.ExecContext(ctx, replaceModelsByController, arg.NamespaceID, arg.ControllerName)
	return err
}

const setModelMeta = `-- name: SetModelMeta :exec
INSERT INTO model_meta(namespace_id, controller_name, key, value)
VALUES (?, ?, ?, ?)
ON CONFLICT(namespace_id, controller_name, key) DO UPDATE SET value = excluded.value
`

type SetModelMetaParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	Key            string `json:"key"`
	Value          string `json:"value"`
}

func (q *Queries) SetModelMeta(ctx context.Context, arg SetModelMetaParams) error {
	_, err := q.db.ExecContext(ctx, setModelMeta,
		arg.NamespaceID,
		arg.ControllerName,
		arg.Key,
		arg.Value,
	)
	return err
}

const upsertModel = `-- name: UpsertModel :exec
INSERT INTO models(namespace_id, controller_name, model_name, details_json)
VALUES (?, ?, ?, ?)
ON CONFLICT(namespace_id, controller_name, model_name) DO UPDATE
SET details_json = excluded.details_json
`

type UpsertModelParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	ModelName      string `json:"model_name"`
	DetailsJson    string `json:"details_json"`
}

func (q *Queries) UpsertModel(ctx context.Context, arg UpsertModelParams) error {
	_, err := q.db.ExecContext(ctx, upsertModel,
		arg.NamespaceID,
		arg.ControllerName,
		arg.ModelName,
		arg.DetailsJson,
	)
	return err
}
