// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Account struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	DetailsJson    string `json:"details_json"`
}

type BootstrapConfig struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	ConfigJson     string `json:"config_json"`
}

type Controller struct {
	NamespaceID string `json:"namespace_id"`
	Name        string `json:"name"`
	DetailsJson string `json:"details_json"`
}

type ControllerAccess struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	UserID         string `json:"user_id"`
	Access         string `json:"access"`
}

type ControllerMetum struct {
	NamespaceID string `json:"namespace_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
}

type ControllerSigningKey struct {
	ID        string       `json:"id"`
	KeyPem    string       `json:"key_pem"`
	CreatedAt time.Time    `json:"created_at"`
	RetiredAt sql.NullTime `json:"retired_at"`
}

type CookieJar struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	CookiesJson    string `json:"cookies_json"`
}

type Credential struct {
	NamespaceID string `json:"namespace_id"`
	CloudName   string `json:"cloud_name"`
	DetailsJson string `json:"details_json"`
}

type Model struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	ModelName      string `json:"model_name"`
	DetailsJson    string `json:"details_json"`
}

type ModelMetum struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	Key            string `json:"key"`
	Value          string `json:"value"`
}

type Namespace struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	OwnerID   string    `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
}

type NamespaceMember struct {
	NamespaceID string `json:"namespace_id"`
	UserID      string `json:"user_id"`
}

type SigningKey struct {
	ID        string       `json:"id"`
	KeyPem    string       `json:"key_pem"`
	CreatedAt time.Time    `json:"created_at"`
	RetiredAt sql.NullTime `json:"retired_at"`
}

type User struct {
	ID        string         `json:"id"`
	Email     sql.NullString `json:"email"`
	CreatedAt time.Time      `json:"created_at"`
}
