// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: namespaces.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addNamespaceMember = `-- name: AddNamespaceMember :exec
INSERT INTO namespace_members(namespace_id, user_id)
VALUES (?, ?)
ON CONFLICT(namespace_id, user_id) DO NOTHING
`

type AddNamespaceMemberParams struct {
	NamespaceID string `json:"namespace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) AddNamespaceMember(ctx context.Context, arg AddNamespaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, addNamespaceMember, arg.NamespaceID, arg.UserID)
	return err
}

const countNamespacesByName = `-- name: CountNamespacesByName :one
SELECT COUNT(*)
FROM namespaces
WHERE name = ?
`

func (q *Queries) CountNamespacesByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNamespacesByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNamespace = `-- name: CreateNamespace :exec
INSERT INTO namespaces(id, name, owner_id)
VALUES (?, ?, ?)
`

type CreateNamespaceParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) CreateNamespace(ctx context.Context, arg CreateNamespaceParams) error {
	_, err := q.db.ExecContext(ctx, createNamespace, arg.ID, arg.Name, arg.OwnerID)
	return err
}

const deleteNamespaceByID = `-- name: DeleteNamespaceByID :exec
DELETE FROM namespaces
WHERE id = ?
`

func (q *Queries) DeleteNamespaceByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNamespaceByID, id)
	return err
}

const deleteNamespaceMembersByNamespaceID = `-- name: DeleteNamespaceMembersByNamespaceID :exec
DELETE FROM namespace_members
WHERE namespace_id = ?
`

func (q *Queries) DeleteNamespaceMembersByNamespaceID(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteNamespaceMembersByNamespaceID, namespaceID)
	return err
}

const getNamespaceByName = `-- name: GetNamespaceByName :one
SELECT id, name, owner_id, created_at
FROM namespaces
WHERE name = ?
`

func (q *Queries) GetNamespaceByName(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceByName, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getNamespaceMembershipID = `-- name: GetNamespaceMembershipID :one
SELECT n.id
FROM namespaces n
JOIN namespace_members m ON m.namespace_id = n.id
WHERE n.name = ? AND m.user_id = ?
`

type GetNamespaceMembershipIDParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetNamespaceMembershipID(ctx context.Context, arg GetNamespaceMembershipIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceMembershipID, arg.Name, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listNamespaceMemberEmails = `-- name: ListNamespaceMemberEmails :many
SELECT u.email
FROM users u
JOIN namespace_members m ON m.user_id = u.id
WHERE m.namespace_id = ?
ORDER BY u.email ASC
`

func (q *Queries) ListNamespaceMemberEmails(ctx context.Context, namespaceID string) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listNamespaceMemberEmails, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var email sql.NullString
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamespacesForUser = `-- name: ListNamespacesForUser :many
SELECT n.id, n.name, n.owner_id, n.created_at
FROM namespaces n
JOIN namespace_members m ON m.namespace_id = n.id
WHERE m.user_id = ?
ORDER BY n.name ASC
`

func (q *Queries) ListNamespacesForUser(ctx context.Context, userID string) ([]Namespace, error) {
	rows, err := q.db.QueryContext(ctx, listNamespacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Namespace{}
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNamespaceMember = `-- name: RemoveNamespaceMember :exec
DELETE FROM namespace_members
WHERE namespace_id = ? AND user_id = ?
`

type RemoveNamespaceMemberParams struct {
	NamespaceID string `json:"namespace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) RemoveNamespaceMember(ctx context.Context, arg RemoveNamespaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeNamespaceMember, arg.NamespaceID, arg.UserID)
	return err
}
