// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddNamespaceMember(ctx context.Context, arg AddNamespaceMemberParams) error
	CountControllerByName(ctx context.Context, arg CountControllerByNameParams) (int64, error)
	CountModelByName(ctx context.Context, arg CountModelByNameParams) (int64, error)
	CountNamespacesByName(ctx context.Context, name string) (int64, error)
	CreateController(ctx context.Context, arg CreateControllerParams) error
	CreateControllerSigningKey(ctx context.Context, arg CreateControllerSigningKeyParams) error
	CreateModel(ctx context.Context, arg CreateModelParams) error
	CreateNamespace(ctx context.Context, arg CreateNamespaceParams) error
	CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) error
	DeleteAccountByController(ctx context.Context, arg DeleteAccountByControllerParams) error
	DeleteAccountsByNamespace(ctx context.Context, namespaceID string) error
	DeleteBootstrapConfigByController(ctx context.Context, arg DeleteBootstrapConfigByControllerParams) error
	DeleteBootstrapConfigByNamespace(ctx context.Context, namespaceID string) error
	DeleteController(ctx context.Context, arg DeleteControllerParams) error
	DeleteControllerAccessByController(ctx context.Context, arg DeleteControllerAccessByControllerParams) error
	DeleteControllerAccessByNamespace(ctx context.Context, namespaceID string) error
	DeleteControllerAccessByUserID(ctx context.Context, userID string) error
	DeleteControllerMetaByNamespace(ctx context.Context, namespaceID string) error
	DeleteControllerSelectionMeta(ctx context.Context, namespaceID string) error
	DeleteControllersByNamespace(ctx context.Context, namespaceID string) error
	DeleteCookiesByController(ctx context.Context, arg DeleteCookiesByControllerParams) error
	DeleteCookiesByNamespace(ctx context.Context, namespaceID string) error
	DeleteCredentialsByNamespace(ctx context.Context, namespaceID string) error
	DeleteModelByName(ctx context.Context, arg DeleteModelByNameParams) error
	DeleteModelMetaByController(ctx context.Context, arg DeleteModelMetaByControllerParams) error
	DeleteModelMetaByNamespace(ctx context.Context, namespaceID string) error
	DeleteModelsByController(ctx context.Context, arg DeleteModelsByControllerParams) error
	DeleteModelsByNamespace(ctx context.Context, namespaceID string) error
	DeleteNamespaceByID(ctx context.Context, id string) error
	DeleteNamespaceMembersByNamespaceID(ctx context.Context, namespaceID string) error
	DeleteNamespaceMembersByUserID(ctx context.Context, userID string) error
	FindControllerByEndpoints(ctx context.Context, namespaceID string) ([]FindControllerByEndpointsRow, error)
	GetAccountByController(ctx context.Context, arg GetAccountByControllerParams) (string, error)
	GetBootstrapConfigByController(ctx context.Context, arg GetBootstrapConfigByControllerParams) (string, error)
	GetControllerAccess(ctx context.Context, arg GetControllerAccessParams) (string, error)
	GetControllerByName(ctx context.Context, arg GetControllerByNameParams) (string, error)
	GetControllerMeta(ctx context.Context, arg GetControllerMetaParams) (string, error)
	GetCookiesByController(ctx context.Context, arg GetCookiesByControllerParams) (string, error)
	GetCredentialByCloud(ctx context.Context, arg GetCredentialByCloudParams) (string, error)
	GetModelByName(ctx context.Context, arg GetModelByNameParams) (string, error)
	GetModelBySuffix(ctx context.Context, arg GetModelBySuffixParams) (string, error)
	GetModelMeta(ctx context.Context, arg GetModelMetaParams) (string, error)
	GetModelNameBySuffix(ctx context.Context, arg GetModelNameBySuffixParams) (string, error)
	GetNamespaceByName(ctx context.Context, name string) (Namespace, error)
	GetNamespaceMembershipID(ctx context.Context, arg GetNamespaceMembershipIDParams) (string, error)
	GetUserEmailByID(ctx context.Context, id string) (sql.NullString, error)
	GetUserIDByEmail(ctx context.Context, email sql.NullString) (string, error)
	ListActiveControllerSigningKeys(ctx context.Context) ([]ControllerSigningKey, error)
	ListActiveSigningKeys(ctx context.Context) ([]SigningKey, error)
	ListControllerSigningKeys(ctx context.Context) ([]ControllerSigningKey, error)
	ListControllersByNamespace(ctx context.Context, namespaceID string) ([]ListControllersByNamespaceRow, error)
	ListCredentialsByNamespace(ctx context.Context, namespaceID string) ([]ListCredentialsByNamespaceRow, error)
	ListModelsByController(ctx context.Context, arg ListModelsByControllerParams) ([]ListModelsByControllerRow, error)
	ListNamespaceMemberEmails(ctx context.Context, namespaceID string) ([]sql.NullString, error)
	ListNamespacesForUser(ctx context.Context, userID string) ([]Namespace, error)
	ListSigningKeys(ctx context.Context) ([]SigningKey, error)
	MigrateControllerAccessUserID(ctx context.Context, arg MigrateControllerAccessUserIDParams) error
	MigrateNamespaceMembersUserID(ctx context.Context, arg MigrateNamespaceMembersUserIDParams) error
	ReassignNamespaceOwnership(ctx context.Context, arg ReassignNamespaceOwnershipParams) error
	RemoveNamespaceMember(ctx context.Context, arg RemoveNamespaceMemberParams) error
	ReplaceModelsByController(ctx context.Context, arg ReplaceModelsByControllerParams) error
	RetireControllerSigningKey(ctx context.Context, id string) error
	RetireSigningKey(ctx context.Context, id string) error
	SetControllerAccess(ctx context.Context, arg SetControllerAccessParams) error
	SetControllerMeta(ctx context.Context, arg SetControllerMetaParams) error
	SetModelMeta(ctx context.Context, arg SetModelMetaParams) error
	UpdateController(ctx context.Context, arg UpdateControllerParams) error
	UpsertAccountByController(ctx context.Context, arg UpsertAccountByControllerParams) error
	UpsertBootstrapConfigByController(ctx context.Context, arg UpsertBootstrapConfigByControllerParams) error
	UpsertCookiesByController(ctx context.Context, arg UpsertCookiesByControllerParams) error
	UpsertCredentialByCloud(ctx context.Context, arg UpsertCredentialByCloudParams) error
	UpsertModel(ctx context.Context, arg UpsertModelParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
