// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package sqlc

import (
	"context"
)

const deleteAccountByController = `-- name: DeleteAccountByController :exec
DELETE FROM accounts
WHERE namespace_id = ? AND controller_name = ?
`

type DeleteAccountByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

func (q *Queries) DeleteAccountByController(ctx context.Context, arg DeleteAccountByControllerParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccountByController, arg.NamespaceID, arg.ControllerName)
	return err
}

const deleteAccountsByNamespace = `-- name: DeleteAccountsByNamespace :exec
DELETE FROM accounts
WHERE namespace_id = ?
`

func (q *Queries) DeleteAccountsByNamespace(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountsByNamespace, namespaceID)
	return err
}

const deleteBootstrapConfigByController = `-- name: DeleteBootstrapConfigByController :exec
DELETE FROM bootstrap_config
WHERE namespace_id = ? AND controller_name = ?
`

type DeleteBootstrapConfigByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

func (q *Queries) DeleteBootstrapConfigByController(ctx context.Context, arg DeleteBootstrapConfigByControllerParams) error {
	_, err := q.db.ExecContext(ctx, deleteBootstrapConfigByController, arg.NamespaceID, arg.ControllerName)
	return err
}

const deleteBootstrapConfigByNamespace = `-- name: DeleteBootstrapConfigByNamespace :exec
DELETE FROM bootstrap_config
WHERE namespace_id = ?
`

func (q *Queries) DeleteBootstrapConfigByNamespace(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteBootstrapConfigByNamespace, namespaceID)
	return err
}

const deleteControllersByNamespace = `-- name: DeleteControllersByNamespace :exec
DELETE FROM controllers
WHERE namespace_id = ?
`

func (q *Queries) DeleteControllersByNamespace(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteControllersByNamespace, namespaceID)
	return err
}

const deleteCookiesByController = `-- name: DeleteCookiesByController :exec
DELETE FROM cookie_jars
WHERE namespace_id = ? AND controller_name = ?
`

type DeleteCookiesByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

func (q *Queries) DeleteCookiesByController(ctx context.Context, arg DeleteCookiesByControllerParams) error {
	_, err := q.db.ExecContext(ctx, deleteCookiesByController, arg.NamespaceID, arg.ControllerName)
	return err
}

const deleteCookiesByNamespace = `-- name: DeleteCookiesByNamespace :exec
DELETE FROM cookie_jars
WHERE namespace_id = ?
`

func (q *Queries) DeleteCookiesByNamespace(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteCookiesByNamespace, namespaceID)
	return err
}

const deleteCredentialsByNamespace = `-- name: DeleteCredentialsByNamespace :exec
DELETE FROM credentials
WHERE namespace_id = ?
`

func (q *Queries) DeleteCredentialsByNamespace(ctx context.Context, namespaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteCredentialsByNamespace, namespaceID)
	return err
}

const getAccountByController = `-- name: GetAccountByController :one
SELECT details_json
FROM accounts
WHERE namespace_id = ? AND controller_name = ?
`

type GetAccountByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

func (q *Queries) GetAccountByController(ctx context.Context, arg GetAccountByControllerParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getAccountByController, arg.NamespaceID, arg.ControllerName)
	var details_json string
	err := row.Scan(&details_json)
	return details_json, err
}

const getBootstrapConfigByController = `-- name: GetBootstrapConfigByController :one
SELECT config_json
FROM bootstrap_config
WHERE namespace_id = ? AND controller_name = ?
`

type GetBootstrapConfigByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

func (q *Queries) GetBootstrapConfigByController(ctx context.Context, arg GetBootstrapConfigByControllerParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getBootstrapConfigByController, arg.NamespaceID, arg.ControllerName)
	var config_json string
	err := row.Scan(&config_json)
	return config_json, err
}

const getCookiesByController = `-- name: GetCookiesByController :one
SELECT cookies_json
FROM cookie_jars
WHERE namespace_id = ? AND controller_name = ?
`

type GetCookiesByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
}

func (q *Queries) GetCookiesByController(ctx context.Context, arg GetCookiesByControllerParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCookiesByController, arg.NamespaceID, arg.ControllerName)
	var cookies_json string
	err := row.Scan(&cookies_json)
	return cookies_json, err
}

const getCredentialByCloud = `-- name: GetCredentialByCloud :one
SELECT details_json
FROM credentials
WHERE namespace_id = ? AND cloud_name = ?
`

type GetCredentialByCloudParams struct {
	NamespaceID string `json:"namespace_id"`
	CloudName   string `json:"cloud_name"`
}

func (q *Queries) GetCredentialByCloud(ctx context.Context, arg GetCredentialByCloudParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByCloud, arg.NamespaceID, arg.CloudName)
	var details_json string
	err := row.Scan(&details_json)
	return details_json, err
}

const listCredentialsByNamespace = `-- name: ListCredentialsByNamespace :many
SELECT cloud_name, details_json
FROM credentials
WHERE namespace_id = ?
ORDER BY cloud_name ASC
`

type ListCredentialsByNamespaceRow struct {
	CloudName   string `json:"cloud_name"`
	DetailsJson string `json:"details_json"`
}

func (q *Queries) ListCredentialsByNamespace(ctx context.Context, namespaceID string) ([]ListCredentialsByNamespaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialsByNamespace, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsByNamespaceRow{}
	for rows.Next() {
		var i ListCredentialsByNamespaceRow
		if err := rows.Scan(&i.CloudName, &i.DetailsJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccountByController = `-- name: UpsertAccountByController :exec
INSERT INTO accounts(namespace_id, controller_name, details_json)
VALUES (?, ?, ?)
ON CONFLICT(namespace_id, controller_name) DO UPDATE
SET details_json = excluded.details_json
`

type UpsertAccountByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	DetailsJson    string `json:"details_json"`
}

func (q *Queries) UpsertAccountByController(ctx context.Context, arg UpsertAccountByControllerParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccountByController, arg.NamespaceID, arg.ControllerName, arg.DetailsJson)
	return err
}

const upsertBootstrapConfigByController = `-- name: UpsertBootstrapConfigByController :exec
INSERT INTO bootstrap_config(namespace_id, controller_name, config_json)
VALUES (?, ?, ?)
ON CONFLICT(namespace_id, controller_name) DO UPDATE
SET config_json = excluded.config_json
`

type UpsertBootstrapConfigByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	ConfigJson     string `json:"config_json"`
}

func (q *Queries) UpsertBootstrapConfigByController(ctx context.Context, arg UpsertBootstrapConfigByControllerParams) error {
	_, err := q.db.ExecContext(ctx, upsertBootstrapConfigByController, arg.NamespaceID, arg.ControllerName, arg.ConfigJson)
	return err
}

const upsertCookiesByController = `-- name: UpsertCookiesByController :exec
INSERT INTO cookie_jars(namespace_id, controller_name, cookies_json)
VALUES (?, ?, ?)
ON CONFLICT(namespace_id, controller_name) DO UPDATE
SET cookies_json = excluded.cookies_json
`

type UpsertCookiesByControllerParams struct {
	NamespaceID    string `json:"namespace_id"`
	ControllerName string `json:"controller_name"`
	CookiesJson    string `json:"cookies_json"`
}

func (q *Queries) UpsertCookiesByController(ctx context.Context, arg UpsertCookiesByControllerParams) error {
	_, err := q.db.ExecContext(ctx, upsertCookiesByController, arg.NamespaceID, arg.ControllerName, arg.CookiesJson)
	return err
}

const upsertCredentialByCloud = `-- name: UpsertCredentialByCloud :exec
INSERT INTO credentials(namespace_id, cloud_name, details_json)
VALUES (?, ?, ?)
ON CONFLICT(namespace_id, cloud_name) DO UPDATE
SET details_json = excluded.details_json
`

type UpsertCredentialByCloudParams struct {
	NamespaceID string `json:"namespace_id"`
	CloudName   string `json:"cloud_name"`
	DetailsJson string `json:"details_json"`
}

func (q *Queries) UpsertCredentialByCloud(ctx context.Context, arg UpsertCredentialByCloudParams) error {
	_, err := q.db.ExecContext(ctx, upsertCredentialByCloud, arg.NamespaceID, arg.CloudName, arg.DetailsJson)
	return err
}
