// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getUserEmailByID = `-- name: GetUserEmailByID :one
SELECT email
FROM users
WHERE id = ?
`

func (q *Queries) GetUserEmailByID(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getUserEmailByID, id)
	var email sql.NullString
	err := row.Scan(&email)
	return email, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id
FROM users
WHERE email = ?
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByEmail, email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users(id, email)
VALUES (?, ?)
ON CONFLICT(id) DO UPDATE SET email = excluded.email
`

type UpsertUserParams struct {
	ID    string         `json:"id"`
	Email sql.NullString `json:"email"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser, arg.ID, arg.Email)
	return err
}
